config/routes.rb
Rails.application.routes.draw do


  get 'home/index'

  get 'notifications/index'
  resources :mygroups do
      member do
        post :new_member
        delete :delete_member

      end
   end

  # resources :mygroups
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

 resources :friendships

  # resources :users

  resources :users do
    post :addfriend
     member do
       get :follow
       get :unfollow
      # post '/newfollow', to: 'users#newfollow'
     end
  end

  root 'users#index'
  # mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mygroup.rb
class Mygroup < ApplicationRecord
  belongs_to :user
  has_many :group_member
  has_many :users, through: :group_member
end

app/controllers/mygroups_controller.rb
class MygroupsController < ApplicationController
  before_action :set_mygroup, only: [:show, :edit, :update, :destroy]

  # GET /mygroups
  # GET /mygroups.json
  def index
    @mygroup=Mygroup.new
     @mygroups = Mygroup.all

  end
  def show
    @mygroup=Mygroup.new
     @mygroups = Mygroup.all
    @usergroup=GroupMember.all
    @users=User.all
    @selectedgroup=Mygroup.find(params[:id])

  end
  def new
    @mygroup=Mygroup.new
  end

  def create
    # @mygroup = current_user.mygroups.build(mygroup_params)
    # @mygroup.user_id = current_user.id
    #
     @mygroup = Mygroup.new(mygroup_params)

    respond_to do |format|
      if @mygroup.save
        format.html { redirect_to @mygroup, notice: 'Mygroup was successfully created.' }
        format.json { render :show, status: :created, location: @mygroup }
      else
        format.html { render :new }
        format.json { render json: @mygroup.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @mygroup.update(mygroup_params)
        format.html { redirect_to @mygroup, notice: 'Mygroup was successfully updated.' }
        format.json { render :show, status: :ok, location: @mygroup }
      else
        format.html { render :edit }
        format.json { render json: @mygroup.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
     @mygroup = Mygroup.find(params[:id])
    @mygroup.destroy
    respond_to do |format|
      format.html { redirect_to mygroups_url, notice: 'Mygroup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_users

    @usersIds= GroupMember.where(group_id: params[:id]).map { |e| e.user_id }
    respond_with User.where(id: @usersIds)

  end

  # GET /groups/new
  def new_member

    @email = params[:user][:email]
    @group_id=params[:group_id]
    @mygroup = Mygroup.find(params[:id])
    if @email !=""
     @user = User.find_by_email(@email)
      if @user != nil
       if current_user != @user.id
            @userfound = GroupMember.where(:user_id => @user.id , :mygroup_id => @mygroup.id)
            if @userfound.exists? == false
                @GroupMember = GroupMember.new(
                mygroup_id: @mygroup.id,
                user_id: @user.id )
              if @GroupMember.save
              end
            end
       end
     end

 end
 redirect_to mygroup_url

end

  # GET /groups/1/edit
  def delete_member
    @GroupMember = GroupMember.find(params[:id])
    if @GroupMember.destroy
      flash[:notice] = "Group member was successfully destroyed"
      redirect_to mygroups_url
    else
      flash[:notice] = "Unable to remove member."
      redirect_to mygroups_url
    end
    # respond_to do |format|
    #   format.html { redirect_to mygroup_url, notice: 'Group member was successfully destroyed.' }
    #   format.json { head :no_content }
    # end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mygroup
      #@mygroup = Mygroup.find(params[:id])
        @group = Mygroup.where(id: params[:id]).take
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mygroup_params
      params.require(:mygroup).permit(:name , :user_id)
    end
end

app/helpers/mygroups_helper.rb
module MygroupsHelper
end

app/views/mygroups/_form.html.erb
<%= form_for(mygroup) do |f| %>
  <% if mygroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mygroup.errors.count, "error") %> prohibited this mygroup from being saved:</h2>

      <ul>
      <% mygroup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mygroups/edit.html.erb
<h1>Editing Mygroup</h1>

<%= render 'form', mygroup: @mygroup %>

<%= link_to 'Show', @mygroup %> |
<%= link_to 'Back', mygroups_path %>

app/views/mygroups/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="bodyc">

<h1>Mygroups</h1>
<%= form_for(@mygroup) do |f| %>


  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name , placeholder: "Enter Group Name" %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>


  <div class="actions">
    <%= f.submit "Add", class: 'btn btn-success' %>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mygroups.each do |mygroup| %>
    <% if mygroup.user_id == current_user.id %>
      <tr>
        <td><h3><%= mygroup.name %></h3</td>

        <td><%= link_to 'Show', mygroup ,:class=> 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_mygroup_path(mygroup) ,:class=> 'btn btn-primary'%></td>
        <td><%= link_to 'Destroy', mygroup, method: :delete,:class=> 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
      <% end %>
  </tbody>
</table>
</div>

<br>

<!-- <%= link_to 'New Mygroup', new_mygroup_path %> -->

app/views/mygroups/new.html.erb
<h1>New Mygroup</h1>

<%= render 'form', mygroup: @mygroup %>

<%= link_to 'Back', mygroups_path %>

app/views/mygroups/show.html.erb
<div class="bodyc">
  <h1>Groups</h1>
  <div style="margin-left:60px;">

      <div id="group-form" >
      <%= form_for(@mygroup) do |f| %>


        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name , placeholder: "Enter Group Name" %>
        </div>
        <div class="field">
          <%= f.hidden_field :user_id, :value => current_user.id %>
        </div>


        <div class="actions">
          <%= f.submit "Add", class: 'btn btn-success' %>
        </div>
      <% end %>
  </div>
</div>

<br/>
<div style="width:30%;float: left;">
            <table class="table">
              <caption><h2>My Groups</h2></caption>
              <tbody>
                <% @mygroups.each do |mygroup| %>
                <% if mygroup.user_id == current_user.id %>
                  <tr>
                    <td><%= mygroup.name %></td>

                    <td><%= link_to 'Show', mygroup ,:class=> 'btn btn-primary' %></td>
                    <td><%= link_to 'Edit', edit_mygroup_path(mygroup) ,:class=> 'btn btn-primary'%></td>
                    <td><%= link_to 'Destroy', mygroup_path(mygroup), method: :delete,:class=> 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
                  <% end %>
              </tbody>
            </table>
          </div>




                  <div style="width:60%; float:right; ">
                      <h3><%= @selectedgroup.name  %></h3>
                    <%= form_for User.new, url: new_member_mygroup_path do |f| %>
                      <div class="col-md-8">
                        <div class="form-group">
                          <%= f.text_field :email, class: "form-control", placeholder: "Enter email here" %>
                        </div>
                        <div class="field">
                          <%= f.hidden_field :group_id, :value => params[:id] %>
                        </div>
                      </div>
                      <div class="col-md-3">
                          <%= f.submit "Add",:class=>"btn btn-success" %>
                      </div>
                    <% end %>

                  <br>

            <div >
              <br/>
              <div class="row">
                <% @usergroup.each do |user| %>

                  <% if user.mygroup_id == @group.id %>
                    <% @users.each do |username| %>
                  
                        <div class="col-md-2">
                          <div class="container">
                            <h4><%= username.name %></h4>
                            <span id="follow_user<%=user.id%>">
                            <%= link_to(delete_member_mygroup_path(user.id), :method => :delete, :class=> 'btn btn-danger', data: { confirm: 'Are you sure?' }) do %>
                              <i class="icon-remove icon-white"></i>
                              Delete
                            <% end %></span><p></p>
                          </div>
                        </div>
                          </div>

                    <%end %>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div>