config/routes.rb
Rails.application.routes.draw do


  get 'home/index'

  get 'notifications/index'
  resources :mygroups do
      member do
        post :new_member
        delete :delete_member

      end
   end

  # resources :mygroups
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

 resources :friendships

  # resources :users

  resources :users do
    post :addfriend
     member do
       get :follow
       get :unfollow
      # post '/newfollow', to: 'users#newfollow'
     end
  end

  root 'users#index'
  # mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_followable
   acts_as_follower
   has_many :mygroups


has_many :friendships
has_many :friends, :through => :friendships
has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

after_destroy_commit { notify }

def notify
  Notification.create(event: "New Notification\n")
end

 def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
       user.provider = auth.provider
       user.uid = auth.uid
       user.name = auth.info.name
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
     end
 end



#  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
#     data = access_token.info
#     user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
#     if user
#       return user
#     else
#       registered_user = User.where(:email => access_token.info.email).first
#       if registered_user
#         return registered_user
#       else
#         user = User.create(name: data["name"],
#           provider:access_token.provider,
#           email: data["email"],
#           uid: access_token.uid ,
#           password: Devise.friendly_token[0,20],
#         )
#       end
#    end
# end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @user=current_user
    @notifications = Notification.all.reverse


  end
  def addfriend
    @email = params[:user][:email]
    @user = User.find_by_email(params[:user]["email"])
    if current_user!=@user
    #byebug
    @friend_id= @user.id
    @friendship = current_user.friendships.build(:friend_id => @friend_id)
    if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to current_user
    else
      flash[:notice] = "Unable to add friend."
      redirect_to current_user
    end
  else
    flash[:notice] = "Unable to add friend."
    redirect_to current_user
    end


  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="bodyc">
<h3>add friend</h3><%= form_for @user, url:  user_addfriend_path(@user),method: :post do |f| %>
  <div class="col-md-4">
    <div class="form-group">
      <%= f.text_field :email, class: "form-control", placeholder: "Enter email here" %>
    </div>
    <div class="field">

    </div>
  </div>
  <div class="col-md-3">
      <%= f.submit "Add",:class=>"btn btn-success" %>
  </div>
<% end %>
<br/><br/>

<h1>List All Users</h1>
<div style="margin-left:60px;">
<table class="table" >
  <thead>
    <tr>

      <th></th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user, i| %>

      <tr>
      <td><img src="<%= image_path('avtar.png')%>" style="width: 55px; height: 50px;"></td>
        <td><%= user.name %></td>

        <% friend_status = current_user.friendships.exists?(:friend_id =>user.id, :user_id => current_user.id)  ? true : false %>
        <% if(friend_status) %>
        <% friendship_id = current_user.friendships.where("friend_id = ? AND user_id = ?", user.id, current_user.id).first.id %>
          <td >
    <%= link_to "Remove", friendship_path(friendship_id) , :class => 'btn btn-danger', :method => :delete %></td>

        <% elsif(current_user.id==user.id) %>
          <td class="table-success">You</td>
        <% else %>
          <td class="table-info"><%= link_to 'Add Friend', friendships_path(:friend_id => user) ,:class=>"btn btn-success", :method => :post %></td>
        <% end %>

        <% if(current_user.id==user.id) %>
        <td class="table-warning"><%= link_to 'Show', user ,:class=>"btn btn-info"%></td>
        <td><%= link_to 'Edit', edit_user_path(user),:class=>"btn btn-info" %></td>
          <td class="table-success"></td>
        <% else %>
        <!-- <td class="table-danger"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>



<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="bodyc">
<div style="margin-left:70px;">
<h1 class="text-warning">Show User</h1>

<br>
<p>
  <h4  >Name:
  <%= @user.name %></h4>
</p>

<p>
  <h4 >Email:
  <%= @user.email %></h4>
</p>


<h2 class="text-warning">Your Friends</h2>
<div style="width:50%;">
<table class="table">
  <thead>
    <tr>

      <th><h4>Name</h4></th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

  <% for friendship in @user.friendships %>
<tr>
    <td><h3 class="text-info"><%= friendship.friend.name %></h3><td>
    <td><%= link_to "remove", friendship,:class => 'btn btn-danger', :method => :delete %></td>
    <tr>

  <% end %>
</tbody>
</table>
</div>




<h2 class="text-warning">Users added you </h2>
<ul>
  <% for befrinded in @user.inverse_friends %>
  <li><%= h befrinded.name %></li>
  <% end %>
</ul>



<%= link_to 'Edit', edit_user_path(@user),:class=>"btn" %>
<%= link_to 'Back', users_path,:class=>"btn" %>
</div>