config/routes.rb
Rails.application.routes.draw do


  get 'home/index'

  get 'notifications/index'
  resources :mygroups do
      member do
        post :new_member
        delete :delete_member

      end
   end

  # resources :mygroups
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

 resources :friendships

  # resources :users

  resources :users do
    post :addfriend
     member do
       get :follow
       get :unfollow
      # post '/newfollow', to: 'users#newfollow'
     end
  end

  root 'users#index'
  # mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yalanotlob</title>
    <%= csrf_meta_tags %>
    <link href="/assets/bootstrap1.min.css?body=1" media="screen" rel="stylesheet">
    <!-- <script src="js/jquery1.min.js"></script>
    <script src="js/bootstrap1.min.js"></script> -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
    body
    {
      background-image: url('<%=image_path("food.jpg")%>');

    }
    .bodyc
    {
      background-color: white;
      width: 70%;
      height:550px;
      margin-left:150px;
      overflow: scroll;

    }
    .login
    {
      background-image: url('<%=image_path("login.jpg")%>');
      width: 100%;
      height: 100%;
    }
    .fontcolor
    {
      color: pink;
    }
    </style>

  </head>

  <body>
    <!--
    <% if user_signed_in? %>
    <% link_to 'logout', destroy_user_session_path ,method: :delete %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>-->
    <% if user_signed_in? %>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to 'Home', home_index_path%></li>
        <li><%= link_to 'Friends', users_path%></li>
        <li><%= link_to 'Groups', mygroups_path%></li>

        <li class="active"><a href="#orders">Orders <span class="sr-only">(current)</span></a></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">


                <!-- <li><img src="/images/logooo.png" class="img-circle" style="width: 35px; height: 48px;"><li> -->

                <li><%= render "notifications/notification_center", notifications: @notifications %>
<li>



                <li><a href="#"><%= current_user.name %></a></li>
                <% if user_signed_in? %>
                <li><%= link_to 'logout', destroy_user_session_path ,method: :delete %></li>
                <% end %>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
        <% end %>
    <%= yield %>
  </body>
</html>